# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yard < Formula
  desc "CLI for Trainyard — ephemeral Kubernetes PR preview environments"
  homepage "https://github.com/Emilvorre/trainyard"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.0.0/yard_darwin_amd64.tar.gz"
      sha256 "867e1b38e5bcacf9ffaa949fc19ff46be45f2204d710515f94c9e3af17100b86"

      define_method(:install) do
        bin.install "yard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.0.0/yard_darwin_arm64.tar.gz"
      sha256 "b49d23b31e1f97090f02a6bd2de1f9eac4b002b8cf866f8408ca88edff12d7e2"

      define_method(:install) do
        bin.install "yard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.0.0/yard_linux_amd64.tar.gz"
      sha256 "03cd7fad12dd0cab4fa5873b1f2545ba67286f9b37e9d7f62fd7c4b27cd47dfb"
      define_method(:install) do
        bin.install "yard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.0.0/yard_linux_arm64.tar.gz"
      sha256 "d3769315f9f8fc422dde967f45a0683ea9b2755510d0cb72f4d548a70a241dfc"
      define_method(:install) do
        bin.install "yard"
      end
    end
  end

  test do
    system "#{bin}/yard", "--help"
  end
end
