# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yard < Formula
  desc "CLI for Trainyard — ephemeral Kubernetes PR preview environments"
  homepage "https://github.com/Emilvorre/trainyard"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.1.2/yard_darwin_amd64.tar.gz"
      sha256 "b7543ced527018bdc5c5b443d2e444bd85614d6460f28c498e30eca84e8575d1"

      define_method(:install) do
        bin.install "yard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.1.2/yard_darwin_arm64.tar.gz"
      sha256 "4593c70a037fa9be3ef9f08fdbbaf0d24b41b78b9056614e3881d81f903e3b75"

      define_method(:install) do
        bin.install "yard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.1.2/yard_linux_amd64.tar.gz"
      sha256 "72c6bcd08c247b6157760f0cdd8ae2ac2dc2a9b0de4cb51297ca02cb0a17e0cb"
      define_method(:install) do
        bin.install "yard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.1.2/yard_linux_arm64.tar.gz"
      sha256 "008168b39d40833c0196ae22e47797eb9fd231aaaf4149e2d196c8f5273f17b4"
      define_method(:install) do
        bin.install "yard"
      end
    end
  end

  test do
    system "#{bin}/yard", "--help"
  end
end
