# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yard < Formula
  desc "CLI for Trainyard — ephemeral Kubernetes PR preview environments"
  homepage "https://github.com/Emilvorre/trainyard"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.1.0/yard_darwin_amd64.tar.gz"
      sha256 "194e3055abcc8197b0c6cf9a9e0260a9a73cdbf883a796825163cc273475dd89"

      define_method(:install) do
        bin.install "yard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.1.0/yard_darwin_arm64.tar.gz"
      sha256 "0dea04a762b3b78b8a590818f883b5c8ca7b1ed6155bcee9ff800f2456c1dbfd"

      define_method(:install) do
        bin.install "yard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.1.0/yard_linux_amd64.tar.gz"
      sha256 "5d10fad0f625ed48fd43bdd869b5e82dabdbc851039da46964f0202c88f1a573"
      define_method(:install) do
        bin.install "yard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Emilvorre/trainyard/releases/download/v1.1.0/yard_linux_arm64.tar.gz"
      sha256 "b3323e7d8e2bfdb8bf95a085e82190d602f30e1c53ae4c43d30e3d8045e2010a"
      define_method(:install) do
        bin.install "yard"
      end
    end
  end

  test do
    system "#{bin}/yard", "--help"
  end
end
